### ISSUE TITLE
Does this mod work with both of the main Waystone Mods for Fabric?

### ISSUE THREAD

**Issue by Zarepheth** [lynnpye/waymaker#3]
The descriptions mentions "[Waystones](https://www.curseforge.com/minecraft/mc-mods/waystones)" by @BlayTheNinth, but the modpack on which I've based my CurseForge profile is using "[Fabric Waystones](https://www.curseforge.com/minecraft/mc-mods/fabric-waystones)" by @LordDeatHunter.

So, if it works with both, please let us know.

If not, please turn this into a feature request for it to support both.

**Comment by LordDeatHunter** [comment]
As far as I can tell, this is a forge-only mod. 🤔

**Comment by Zarepheth** [comment]
@LordDeatHunter I'm no expert at Java code or Minecraft mod authoring, so if the description or title fails to mention a required mod-loader I might make some assumptions (potentially faulty...)

Anyway, this mod was mentioned in one of @xaero's maps' issues, so I came here and saw that the author specified just @BlayTheNinth's mod, but since the "[Better MC [FABRIC] 1.19.2](https://www.curseforge.com/minecraft/modpacks/better-mc-fabric)" modpack on which my CurseForge Overwolf client's profile is based uses your Waystone mod, I thought I'd ask the question (not even wondering whether this mod works on Fabric).

**Comment by lynnpye** [comment]
This mod is Forge only and only supports interaction with the Waystones mod by BlayTheNinth.
